remote_theme: just-the-docs/just-the-docs

logo: "/assets/images/logo.png"

aux_links:
  "Planetary on Github":
    - "//github.com/planetary-social"

aux_links_new_tab: false

heading_anchors: true

search_enabled: true
