remote_theme: just-the-docs/just-the-docs

baseurl: "/protocol-documentation"

title: Planetary Developer Portal
description: Social media for humans not algorithms

logo: "/assets/images/logo.svg"

aux_links:
  "Planetary on Github":
    - "//github.com/planetary-social"
  "Website":
    - "//planetary.social"

aux_links_new_tab: false

heading_anchors: true

search_enabled: true

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/planetary-social/protocol-documentation"
gh_edit_branch: "master"
gh_edit_source: docs 
gh_edit_view_mode: "tree" 
